#!/usr/bin/perl -w

# user/usys.pl
# Generate usys.S, the stubs for syscalls.
# 基于 include/syscall/sysnum.h 中的系统调用号

print "# generated by usys.pl - do not edit\n";
print "# User-space system call stubs\n\n";

print ".text\n\n";

sub entry {
    my $name = shift;
    my $num = shift;
    
    print ".global $name\n";
    print "$name:\n";
    print " li a7, $num\n";
    print " ecall\n";
    print " ret\n\n";
}

# 使用与内核一致的系统调用号
print "# Process control syscalls\n";
entry("fork", "16");     # SYS_fork
entry("exit", "17");     # SYS_exit  
entry("wait", "18");     # SYS_wait
entry("kill", "19");     # SYS_kill
entry("getpid", "20");   # SYS_getpid

print "# File operation syscalls\n";
entry("open", "21");     # SYS_open
entry("close", "22");    # SYS_close
entry("read", "23");     # SYS_read
entry("write", "24");    # SYS_write

print "# Memory management syscalls\n";
entry("sbrk", "25");     # SYS_sbrk

print "# Memory mapping syscalls\n";
entry("brk", "1");       # SYS_brk
entry("mmap", "2");      # SYS_mmap
entry("munmap", "3");    # SYS_munmap

print "# End of generated stubs\n";