#!/usr/bin/perl -w

print "# generated by usys.pl - do not edit\n";
print ".text\n\n";

sub entry {
    my $name = shift;
    my $num = shift;
    
    print ".global $name\n";
    print "$name:\n";
    print " li a7, $num\n";
    print " ecall\n";
    print " ret\n\n";
}

# 系统调用 1-6
print "# Memory management syscalls\n";
entry("brk", "1");       # SYS_brk
entry("mmap", "2");      # SYS_mmap
entry("munmap", "3");    # SYS_munmap
entry("copyin", "4");    # SYS_copyin
entry("copyout", "5");   # SYS_copyout
entry("copyinstr", "6"); # SYS_copyinstr

# 系统调用 16-26
print "# Process control syscalls\n";
entry("fork", "16");     # SYS_fork
entry("exit", "17");     # SYS_exit  
entry("wait", "18");     # SYS_wait
entry("kill", "19");     # SYS_kill
entry("getpid", "20");   # SYS_getpid
entry("yield", "21");

print "# File operation syscalls\n";
entry("pipe", "22");     # SYS_pipe
entry("open", "23");     # SYS_open
entry("close", "24");    # SYS_close
entry("read", "25");     # SYS_read
entry("write", "26");    # SYS_write

print "# Memory management syscalls\n";
entry("sbrk", "27");     # SYS_sbrk

print "# Other syscalls\n";
entry("getppid", "28");  # SYS_getppid

# 扩展的文件系统调用 (29-40)
print "# Extended file system syscalls\n";
entry("lseek", "29");    # SYS_lseek
entry("stat", "30");     # SYS_stat
entry("fstat", "31");    # SYS_fstat
entry("mkdir", "32");    # SYS_mkdir
entry("chdir", "33");    # SYS_chdir
entry("getcwd", "34");   # SYS_getcwd
entry("link", "35");     # SYS_link
entry("unlink", "36");   # SYS_unlink
entry("dup", "37");      # SYS_dup
entry("dup2", "38");     # SYS_dup2

# 符号链接支持
print "# Symbolic link syscalls (optional)\n";
entry("symlink", "39");  # SYS_symlink
entry("readlink", "40"); # SYS_readlink

print "# End of generated stubs\n";
