#!/usr/bin/perl -w

print "# generated by usys.pl - do not edit\n";
print ".text\n\n";

sub entry {
    my $name = shift;
    my $num = shift;
    
    print ".global $name\n";
    print "$name:\n";
    print " li a7, $num\n";
    print " ecall\n";
    print " ret\n\n";
}

# 系统调用 1-6
print "# Memory management syscalls\n";
entry("brk", "1");       # SYS_brk
entry("mmap", "2");      # SYS_mmap
entry("munmap", "3");    # SYS_munmap
entry("copyin", "4");    # SYS_copyin
entry("copyout", "5");   # SYS_copyout
entry("copyinstr", "6"); # SYS_copyinstr

# 系统调用 16-26
print "# Process control syscalls\n";
entry("fork", "16");     # SYS_fork
entry("exit", "17");     # SYS_exit  
entry("wait", "18");     # SYS_wait
entry("kill", "19");     # SYS_kill
entry("getpid", "20");   # SYS_getpid
entry("yield", "21");

print "# File operation syscalls\n";
entry("pipe", "22");     # SYS_pipe
entry("open", "23");     # SYS_open
entry("close", "24");    # SYS_close
entry("read", "25");     # SYS_read
entry("write", "26");    # SYS_write

print "# Memory management syscalls\n";
entry("sbrk", "27");     # SYS_sbrk

print "# Other syscalls\n";
entry("getppid", "28");

print "# End of generated stubs\n";
